server:
  port: 9000

spring:
  config:
    activate:
      on-profile: default
  security:
    user:
      name: user1
      password: password
    oauth2:
      authorizationserver:
        issuer: http://auth-server:9000
        client:
          spring-cloud-client:
            registration:
              client-id: "spring-cloud-client"
              client-secret: "{noop}secret"
              client-name: "Spring Cloud Client"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://127.0.0.1:8080/login/oauth2/code/spring-cloud-client
                - http://127.0.0.1:8080/authorized
              scopes:
                - openid
                - articles.read
